package com.example.sample.domain.entity;

/**
 * 自動生成されるIDを管理するインターフェース
 *
 * @author YutaMori
 */
public interface AutoGeneratedIdManageable {

    /**
     * IDを取得するメソッド
     *
     * @return 自動生成されるID
     */
    String getAutoGeneratedId();

    /**
     * IDを設定するメソッド
     *
     * @param id ID
     */
    void setAutoGeneratedId(String id);
}
