package com.example.sample.domain.entity;

import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * 共通のエンティティ
 *
 * @author YutaMori
 */
@Getter
@Setter
public abstract class BaseEntity {

    /**
     * 論理削除フラグ
     */
    private boolean deleteFlg;

    /**
     * 作成者ID
     */
    private String inputUserId;

    /**
     * 作成日時
     */
    private LocalDateTime inputDatetime;

    /**
     * 更新者ID
     */
    private String UpdateUserId;

    /**
     * 更新日時
     */
    private LocalDateTime UpdateDatetime;

    /**
     * バージョン
     */
    private Long version;

    /**
     * コンストラクタ
     */
    protected BaseEntity() {
    }

    public abstract String getAutoGeneratedId();
}
