package com.example.sample.domain.entity;


import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

/**
 * SYSTEM_CONFIGのエンティティ
 *
 * @author YutaMori
 */
@Getter
@Setter
@Table("SYSTEM_CONFIG")
public class SystemConfig extends BaseEntity implements AutoGeneratedIdManageable {

    /**
     * ID
     */
    @Id
    private String systemConfigId;

    /**
     * ユーザーをロックする失敗回数
     */
    private int userLockTimes;

    /**
     * {@inheritDoc}
     */
    @Override
    public String getAutoGeneratedId() {
        return this.systemConfigId;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void setAutoGeneratedId(String id){
        this.systemConfigId = id;
    }
}
