package com.example.sample.domain.entity;

import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

/**
 * Userのエンティティ
 *
 * @author YutaMori
 */
@Getter
@Setter
@Table("USER")
public class User extends BaseEntity implements AutoGeneratedIdManageable {

    /**
     * ID
     */
    @Id
    private String userId;

    /**
     * ユーザー名
     */
    private String userName;

    /**
     * メイルアドレス
     */
    private String mailAddress;

    /**
     * 登録状態
     */
    private String registrationStatus;

    /**
     * ログインエラー回数
     */
    private int errorCount;

    /**
     * ユーザーロックフラグ
     */
    private String lockedFlg;

    /**
     * {@inheritDoc}
     */
    @Override
    public String getAutoGeneratedId() {
        return this.userId;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void setAutoGeneratedId(String id) {
        this.userId = id;
    }
}
