package com.example.sample.domain.entity;

import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;
import org.springframework.stereotype.Repository;

/**
 * ユーザー
 *
 * @author YutaMori
 */
@Getter
@Setter
@Table("USERS")
public class Users extends BaseEntity implements AutoGeneratedIdManageable {

    /**
     * ユーザーID
     */
    @Id
    private String userId;

    /**
     * ユーザー名
     */
    private String userName;

    /**
     * メールアドレス
     */
    private String mailAddress;

    /**
     * ログインID
     */
    private String loginId;

    /**
     * 初期パスワード
     */
    private String initialPassword;

    /**
     * パスワード
     */
    private String password;

    /**
     * 登録状態
     */
    private String registrationStatus;

    /**
     * 権限の種類
     */
    private String authorizationType;

    /**
     * エラーカウント
     */
    private int errorCount;

    /**
     * ロック状態
     */
    private String lockedFlg;

    /**
     * {@inheritDoc}
     */
    @Override
    public String getAutoGeneratedId() {
        return this.userId;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void setAutoGeneratedId(String id) {
        this.userId = id;
    }
}
