CREATE TABLE SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL PRIMARY KEY
    , SESSION_ID CHAR(36) NOT NULL
    , CREATION_TIME NUMERIC(19, 0) NOT NULL
    , LAST_ACCESS_TIME NUMERIC(19, 0) NOT NULL
    , MAX_INACTIVE_INTERVAL INT NOT NULL
    , EXPIRY_TIME NUMERIC(19, 0) NOT NULL
    , PRINCIPAL_NAME VARCHAR(100)
);

CREATE UNIQUE INDEX UQ_IDX_SPRING_SESSION_01 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX IDX_SPRING_SESSION_02 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IDX_SPRING_SESSION_03 ON SPRING_SESSION (PRINCIPAL_NAME);